version: 2

aliases:
  - &node_modules_cache_params
    key: v1-node_modules-{{ .Branch }}-{{ checksum "./package-lock.json" }}
    paths:
      - node_modules
  - &restore_cache
    name: Restore Cache.
    <<: *node_modules_cache_params
  - &save_cache
    name: Saving Cache.
    <<: *node_modules_cache_params

jobs:
  build:
    docker:
      - image: circleci/node:10.15.3
    working_directory: /home/circleci/project
    steps:
      - checkout
      - run:
          name: Update npm module.
          command: sudo npm install -g npm@latest
      - restore_cache: *restore_cache
      - run:
          name: Install package.
          command: npm install
      - save_cache: *save_cache
      - run:
          name: Build app.
          command: npm run build
workflows:
  version: 2
  build:
    jobs:
      - build
